version: '3.3'

services:

    mementoembed:
        image: oduwsdl/mementoembed:latest
        restart: "no"

    mongodb:
        image: mongo:latest
        restart: "no"

    mementodamage:
        image: erikaris/memento-damage:latest
        restart: "no"
        ports:
            - "32768:80"
        command: "/app/entrypoint.sh"

    raintale:
        depends_on:
            - mementoembed
        image: oduwsdl/raintale:latest
        restart: always
        volumes: 
            - .:/raintale-work
        stdin_open: true
        environment:
            - MEMENTOEMBED_API_ENDPOINT=http://mementoembed:5550

    hypercane:
        depends_on:
            - mongodb
            - mementodamage
        image: hypercane:dev
        build: ./
        command: bash
        restart: always
        volumes:
            - .:/hypercane-work
        stdin_open: true
        environment:
            - HC_CACHE_STORAGE=mongodb://mongodb/csHC


